# %chatreactions_get_score%

words_file_name: "words/dictionary.txt"

interval:
  # in seconds
  min: 900
  max: 1200

# in seconds
time_limit: 30

sounds:
  start: ENTITY_EXPERIENCE_ORB_PICKUP
  win: ENTITY_EXPERIENCE_ORB_PICKUP

rewards:
  top:
    '1':
      message: "1.500$"
      commands:
        - "eco give %player% 1500"
    '2':
      message: "1.000$"
      commands:
        - "eco give %player% 1000"
    '3':
      message: "500$"
      commands:
        - "eco give %player% 500"

messages:
  commands:
    incorrect_usage: "&fCorrect Usage : {0}"
    no_permission: "&fCommande inconnue."
    help:
      - "&7&m------------------&8[&6Help Panel&8]&7&m------------------"
      - "{!chatreactions.command.start}&6/chatreactions start &estart a reaction !"
      - "{!chatreactions.command.stop}&6/chatreactions stop &estop the current reaction !"
      - "&7&m----------------------------------------------"
    start:
      success: "&7[&c&lES&7] La Réaction a été lancé avec succès !"
    stop:
      success: "&7[&c&lES&7] La Réaction a été stoppé avec succès !"
  chat:
    start_messages:
      hover:
        - "&f{0}"
      messages:
        - '                                                       '
        - '&7&l---»                                               '
        - '&7[&6&l!&7] &b&lRÉACTION CHAT&7 [&6&l!&7]                                  '
        - '                                                       '
        - '&f&l|&a&l Passe ta souris dans le chat et recopies         '
        - '&a&lle mot affiché.                                             '
        - '                                                       '
        - '&f&l|&e Vous devez être le plus rapide pour remporter               '
        - '&eles récompenses &e!                                            '
        - '                                                       '
        - '&f&l|&bNombre de Gagnants : 3                                             '
        - '&7&l---»                                                   '
        - '                                                       '

    no_player: '&7[&c&lRéaction&7] &cPersonne n''a trouvé le mot à temps.'

    top:
      template: "&f&l| &bN°{0} &e{1} &7- &a{2}s &7- &d{3}"
      send_total_message: false
      # send this message if send_total_message is set to false
      no_all_player: "&7[&c&lRéaction&7] &cToutes les récompenses n'ont pas été données à temps !"
      message:
        - '&r '
        - "&7---»"
        - "&r "
        - "&dLa réaction est terminé !"
        - "&7 Le mot était : {0} &7(&b/reaction&7)"
        - "&r "
        - "&a&l&nCLASSEMENT RÉACTIONS :"
        - "&r "
        - "{1}"
        - "&r "
        - "&7---»"
        - '&r '