name: ChatReactions
version: 1.0.0
author: nivcoo
main: fr.nivcoo.chatreactions.ChatReactions
softdepend: [ PlaceholderAPI ]
commands:
  chatreactions:
    description: ChatReactions Command
permissions:
  chatreactions.commands:
    default: op
    description: command
  chatreactions.command.start:
    default: op
    description: Start ChatReactions
  chatreactions.command.stop:
    default: op
    description: Stop Current ChatReactions